--DELETES ALL THE TABLES
DROP TABLE ACCOUNT_TRANSACTIONS, INVOICE_ITEM, LINE_ITEM, INVOICE, ACCOUNT, PROVIDER_SERVICE_REGION, CUSTOMER_ADDRESS, PROVIDED_UTILITIES, UTILITY_PROVIDER, UTILITY, CUSTOMER;